# The URL the site will be built for
base_url = "https://joergrings.com"

build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true

theme = "apollo"
taxonomies = [{ name = "tags" }]
title = "Nothing is Unstable"
description = "The personal webpage of Jörg Rings"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
fancy_code = true
mathjax = true
mathjax_dollar_inline_enable = true
theme = "toggle"
toc = true
socials = [
  { name = "bluesky", url = "https://bsky.app/profile/eatyoursoup.bsky.social", icon = "bluesky" },
  { name = "github", url = "https://github.com/jrings/", icon = "github" },
  { name = "linkedin", url = "https://www.linkedin.com/in/joergrings/", icon = "linkedin" }
]
menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/projects", url = "/projects", weight = 2 }
]

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14