# The URL the site will be built for
base_url = "https://joergrings.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "apollo"
taxonomies = [{ name = "tags" }]
title = "Nothing is Unstable"
description = "The personal webpage of Jörg Rings"


[extra]
theme = "auto"
toc = true
socials = [
  { name = "bluesky", url = "https://bsky.app/profile/eatyoursoup.bsky.social", icon = "bluesky" },
  { name = "github", url = "https://github.com/jrings/", icon = "github" },
  { name = "linkedin", url = "https://www.linkedin.com/in/joergrings/", icon = "linkedin" }
]
menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/projects", url = "/projects", weight = 2 }
]

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14